- name: Force Clean and Setup Theos
        run: |
          echo "تنظيف المسارات..."
          sudo rm -rf /tmp/theos
          sudo rm -rf $GITHUB_WORKSPACE/theos
          
          echo "تحميل Theos..."
          git clone --recursive https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
          
          echo "تحميل الـ SDKs المطلوبة..."
          mkdir -p $GITHUB_WORKSPACE/theos/sdks
          curl -L -o $GITHUB_WORKSPACE/theos/sdks/iPhoneOS14.5.sdk.tar.xz https://github.com/theos/sdks/releases/download/latest/iPhoneOS14.5.sdk.tar.xz
          # فك ضغط الـ SDK
          tar -xvf $GITHUB_WORKSPACE/theos/sdks/iPhoneOS14.5.sdk.tar.xz -C $GITHUB_WORKSPACE/theos/sdks/


